import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import DashboardLayout from '../layouts/DashboardLayout';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import DataTable from '../components/DataTable';
import Modal from '../components/Modal';
import Card from '../components/Card';
import { Plus, FileText } from 'lucide-react';
import * as reportsApi from '../api/reportsApi';
import { useRole } from '../hooks/useRole';
import { useAuth } from '../context/AuthContext';
import { formatDateTime, labelify } from '../utils/formatters';
import { REPORT_SCOPES } from '../utils/constants';
import { toast } from 'sonner';

export default function ReportsPage() {
  const { canManageIssues } = useRole();
  const { user } = useAuth();
  const qc = useQueryClient();
  const [modal, setModal] = useState(false);
  const [view, setView] = useState(null);
  const [form, setForm] = useState({ title: '', scope: 'ISSUE', description: '', content: '' });
  const set = (k) => (e) => setForm(f => ({ ...f, [k]: e.target.value }));

  const { data: reports = [], isLoading } = useQuery({
    queryKey: ['reports'],
    queryFn: () => reportsApi.getReports().then(r => r.data).catch(() => []),
  });

  const createMut = useMutation({
    mutationFn: (d) => reportsApi.createReport(d),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['reports'] }); toast.success('Report generated'); setModal(false); },
    onError: () => toast.error('Failed to generate report'),
  });

  const columns = [
    { key: 'id', label: '#', render: r => <span className="text-xs text-bark-400">#{r.id}</span> },
    { key: 'title', label: 'Title', sortable: true, render: r => (
      <button onClick={() => setView(r)} className="font-medium text-forest-600 hover:underline text-left">{r.title}</button>
    )},
    { key: 'scope', label: 'Scope', render: r => <span className="text-xs px-2 py-0.5 rounded-full bg-earth-100 text-bark-600">{r.scope}</span> },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'generatedAt', label: 'Date', render: r => <span className="text-xs text-bark-400">{formatDateTime(r.generatedAt)}</span> },
    { label: 'Actions', render: r => <Button size="sm" variant="ghost" onClick={() => setView(r)}><FileText size={14} /> View</Button> },
  ];

  return (
    <DashboardLayout>
      <PageHeader emoji="📜" title="Reports" description="Analytics and sustainability reports"
        action={canManageIssues && <Button onClick={() => setModal(true)}><Plus size={16} /> Generate Report</Button>}
      />

      <div className="bg-white rounded-2xl border border-bark-400/10 p-4">
        <DataTable columns={columns} data={reports} loading={isLoading} />
      </div>

      {/* Create Modal */}
      <Modal open={modal} onClose={() => setModal(false)} title="Generate Report" size="lg">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-bark-600 mb-1">Report Title</label>
            <input className="w-full border border-bark-400/20 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-forest-600/30" value={form.title} onChange={set('title')} />
          </div>
          <div>
            <label className="block text-sm font-medium text-bark-600 mb-1">Scope</label>
            <select className="w-full border border-bark-400/20 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-forest-600/30" value={form.scope} onChange={set('scope')}>
              {REPORT_SCOPES.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-bark-600 mb-1">Description</label>
            <textarea rows={2} className="w-full border border-bark-400/20 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-forest-600/30" value={form.description} onChange={set('description')} />
          </div>
          <div>
            <label className="block text-sm font-medium text-bark-600 mb-1">Report Content / Summary</label>
            <textarea rows={5} className="w-full border border-bark-400/20 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-forest-600/30" value={form.content} onChange={set('content')} placeholder="Enter report content, findings, or summary…" />
          </div>
          <div className="flex gap-3 justify-end">
            <Button variant="secondary" onClick={() => setModal(false)}>Cancel</Button>
            <Button onClick={() => createMut.mutate({ ...form, generatedBy: user?.name })} loading={createMut.isPending}>Generate</Button>
          </div>
        </div>
      </Modal>

      {/* View Modal */}
      <Modal open={!!view} onClose={() => setView(null)} title={view?.title || ''} size="lg">
        {view && (
          <div className="space-y-3">
            <div className="flex items-center gap-3">
              <span className="text-xs px-2 py-0.5 rounded-full bg-earth-100 text-bark-600">{view.scope}</span>
              <span className="text-xs text-bark-400">by {view.generatedBy} · {formatDateTime(view.generatedAt)}</span>
            </div>
            {view.description && <p className="text-sm text-bark-600">{view.description}</p>}
            <div className="bg-earth-100 rounded-xl p-4 text-sm text-bark-800 whitespace-pre-wrap max-h-64 overflow-y-auto">{view.content || 'No content.'}</div>
          </div>
        )}
      </Modal>
    </DashboardLayout>
  );
}

